version: "3.9"

services:
  yarn:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    entrypoint: yarn
    network_mode: "host"
    volumes:
      - .:/app:delegated
      - ./node_modules:/app/node_modules:cached
